### ISSUE TITLE
Unable to access admin.opencerts.io 

### ISSUE THREAD

**Issue by RP-OIS-SK** [OpenCerts/admin-website#352] opened 2021-07-28 09:13 UTC
My user can't access the admin.opencerts.io this morning 28/7/2021 09:00 - 10:00 
using chrome Version 92.0.4515.107  

![25010714-d436-4024-8840-3756c46f81d2](https://user-images.githubusercontent.com/47696120/127296704-c4d8dcf1-eec5-4683-87f4-92dd5cad4ee5.jpg)

They have no problem previous using the same hardware ledger.  

Please assist to check. 

Thanks. 

RP/ Swee Kiew

**Comment by simboonlong** [comment] 2021-07-28 10:12
hi was not able to replicate, can you get the user to hit retry button if the first login fails?

![ledger](https://user-images.githubusercontent.com/4774314/127305610-8c5e8a48-2e70-4197-b3e0-47ad25ab67f0.png)

**Comment by SP-INDT-OpenCert** [comment] 2021-07-29 02:51
Same issue encountered for our SP users today, already switched notebook with admin access.

**Comment by simboonlong** [comment] 2021-07-29 04:10
duplicate of https://github.com/OpenCerts/admin-website/issues/344

interim solution is to use firefox browser at https://firefox.admin.opencerts.io

**Comment by SP-INDT-OpenCert** [comment] 2021-07-30 04:42
Thanks it worked for us

**Closed** 2021-07-30 04:53 UTC
